version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4
  build-helpers: style/build-helpers@1.3.1

# [major].[minor].[patch]-[prerelease]+[buildmetadata]
semVerRegExp: &semVerRegExp
                /^(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9A-Za-z-][0-9A-Za-z-]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/

references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/repo
  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: ~/repo
      paths: .

executors:
  hedwig:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: hedwig
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - *persist_to_workspace
  test:
    executor: hedwig
    steps:
      - *attach_workspace
      - run: npm test
      - codecov/upload:
          file: .nyc_output/*.json
      - *persist_to_workspace
  publish:
    executor: hedwig
    steps:
      - *attach_workspace
      - build-helpers/authenticate_npm
      - run: npm publish
      - *persist_to_workspace
  github_release:
    executor: hedwig
    steps:
      - *attach_workspace
      - run:
          name: Install Github Release Notes
          command: sudo npm install -g github-release-notes
      - run:
          name: Publish release on GitHub
          command: |
              gren release \
                      --draft \
                      --prerelease \
                      --override \
                      --data-source=commits \
                      --token=$GITHUB_TOKEN

workflows:
  build:
    jobs:
      - install_dependencies:
          context: pi
          filters:
              tags:
                  only: /.*/ # ensure this job does not block publishing via tag
              branches:
                  only: /^pull\/.*$/ # only from forks
      - test:
          context: pi
          requires:
              - install_dependencies
          filters:
              tags:
                  ignore: /.*/ # ignore for all tags
              branches:
                  only: /^pull\/.*$/ # only from forks
      - publish:
            context: pi
            requires:
              - install_dependencies
            filters:
                tags:
                    only: *semVerRegExp # allow publish tag matches any semVer
                branches:
                    ignore: /.*/ # ignore all branch builds
      - github_release:
            context: pi
            requires:
                - publish
            filters:
                tags:
                    only: *semVerRegExp # allow publish tag matches any semVer
                branches:
                    ignore: /.*/ # ignore all branch builds


